// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","id":"1"},"2":{"path":"/","redirect":"/dashboard","parentId":"1","id":"2"},"3":{"path":"/dashboard","parentId":"1","id":"3"},"4":{"path":"/users","parentId":"1","id":"4"},"5":{"path":"/audit","parentId":"1","id":"5"},"6":{"path":"/settings","parentId":"1","id":"6"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "layouts__AdminLayout" */'@/layouts/AdminLayout.tsx')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__dashboard" */'@/pages/dashboard.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__users" */'@/pages/users.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__audit" */'@/pages/audit.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__settings" */'@/pages/settings.tsx')),
},
  };
}
